fix: installing without [toml] extra would cause import errors #80
https://github.com/nedbat/scriv/issues/80

Like this:

```
$ pipx install scriv
$ scriv --help
Traceback (most recent call last):
  File "/home/mg/.local/pipx/venvs/scriv/lib/python3.10/site-packages/scriv/config.py", line 13, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mg/.local/bin/scriv", line 5, in <module>
    from scriv.cli import cli
  File "/home/mg/.local/pipx/venvs/scriv/lib/python3.10/site-packages/scriv/cli.py", line 9, in <module>
    from .collect import collect
  File "/home/mg/.local/pipx/venvs/scriv/lib/python3.10/site-packages/scriv/collect.py", line 11, in <module>
    from .scriv import Scriv
  File "/home/mg/.local/pipx/venvs/scriv/lib/python3.10/site-packages/scriv/scriv.py", line 13, in <module>
    from .changelog import Changelog, Fragment
  File "/home/mg/.local/pipx/venvs/scriv/lib/python3.10/site-packages/scriv/changelog.py", line 10, in <module>
    from .config import Config
  File "/home/mg/.local/pipx/venvs/scriv/lib/python3.10/site-packages/scriv/config.py", line 15, in <module>
    import tomli as tomllib  # type: ignore
ModuleNotFoundError: No module named 'tomli'
```